### ISSUE TITLE
Question: How do I control the CSS Modules class name?

### ISSUE THREAD

**Issue by JawsomeJason** [zcong1993/neutrino-middleware-styles-loader#1]
I would like to make sure my class names fit this format: `[name]__[local]--[hash:base64:5]`

I'm not sure where to set `localIdentName` with postcss in this plugin.

**Comment by zcong1993** [comment]
Now you can use `externalLoaderOptions` to do this, more details please see readme

**Comment by JawsomeJason** [comment]
Thank you so much!  I'm so sorry I missed that

**Comment by zcong1993** [comment]
I just add it, so you should use `v0.0.6`
