### ISSUE TITLE
Note about @neutrinojs/style-loader

### ISSUE THREAD

**Issue by timkelty** [zcong1993/neutrino-middleware-styles-loader#13]
Hi there,

There is alot of crossover with the most recent version `[@neutrinojs/style-loader](https://github.com/mozilla-neutrino/neutrino-dev/tree/master/packages/style-loader)`, which supports alot of these features (extractCSS, custom loaders, css modules).

It might be nice to put a note in your README notifying users there is a first-party option, and what the differences are.

Or - if there are differences that make sense to add to `@neutrinojs/style-loader`, we'd love to see you PR them so the community is using a similar toolset and things are less fragmented.

**Comment by zcong1993** [comment]
updated readme

**Comment by timkelty** [comment]
Thanks!
