### ISSUE TITLE
Some modules resolution issue

### ISSUE THREAD

**Issue by harabara** [zcong1993/neutrino-middleware-styles-loader#2]
Hey,
I'm not sure this is `neutrino-middleware-styles-loader`'s issue, but I really need some clarifications.
[Here](https://github.com/harabara/react-starter) I'm trying to create a monorepo and bootsrap it with [lerna](https://github.com/lerna/lerna). If lerna's `hoist` option is set to `false` everything works fine, but if it's `true` then I get 
```
ERROR in ./src/App.js
Module not found: Error: Can't resolve 'style-loader' in '/projects/react-starter/apps/app1'
...
```
It there anything I can do about it?
Thanks

**Comment by zcong1993** [comment]
[https://github.com/lerna/lerna/blob/master/doc/hoist.md](https://github.com/lerna/lerna/blob/master/doc/hoist.md)

If you set `hoist` to `true`, all the `node_modules` in your individual package raise to `top-level node_modules` , so `loaders` are in `/projects/react-starter/node_modules`.

And `lerna` also put sub `node_modules` to the top-level and share it. So even I add the `top-level node_modules` path to `config.resolveLoader.modules`, it alse cause error. 

Cause `neutrino-preset-react` use `style-loader` in own node_modules `const MODULES = join(__dirname, 'node_modules');` but it raise to top-level.

So I recommend you to set `hoist` to `false`

**Comment by harabara** [comment]
Thanks a lot. I wonder how `neutrino-preset-react` could get around using such a strict resolution. 
So far I was able to bootstrap ~10 projects with lerna, each with dozens of different dependencies and never encountered this problem.
